'use strict';

const fs = require('fs');
const path = require('path');
const { execTool, resolveWorkdir, redactSecrets, SECRET_KEY_RE, defineTool } = require('./exec');

/**
 * Docker tools — generate hardened build artifacts and drive the local Docker
 * daemon (Docker Desktop). Everything delegates to the `docker` CLI; nothing
 * here re-implements the daemon protocol.
 *
 * Security (infrastructure-misconfig checklist): generated Dockerfiles pin the
 * base image, run as a non-root USER, and ship a .dockerignore that keeps
 * secrets out of the build context. The run/build wrappers build their own
 * argument arrays, so `--privileged`, `--pid=host`, and a `/var/run/docker.sock`
 * mount are simply never expressible; secret-valued `--build-arg`s are refused
 * so credentials cannot bake into image history.
 */

const NOTE = '# Generated by AI Fleet — review before use. Pin digests for production.';

const TEMPLATES = Object.freeze({
  node: ({ version = '20.18.1-bookworm-slim', port = 3000, start = 'node server.js' }) =>
    [
      NOTE,
      `FROM node:${version}`,
      'ENV NODE_ENV=production',
      'WORKDIR /app',
      'COPY --chown=node:node package*.json ./',
      'RUN npm ci --omit=dev',
      'COPY --chown=node:node . .',
      'USER node',
      `EXPOSE ${port}`,
      `CMD ${jsonExec(start)}`,
    ].join('\n'),
  python: ({ version = '3.12.7-slim-bookworm', port = 8000, start = 'python main.py' }) =>
    [
      NOTE,
      `FROM python:${version}`,
      'ENV PYTHONDONTWRITEBYTECODE=1 \\',
      '    PYTHONUNBUFFERED=1',
      'RUN useradd --create-home --uid 1000 appuser',
      'WORKDIR /app',
      'COPY --chown=appuser:appuser requirements.txt ./',
      'RUN pip install --no-cache-dir -r requirements.txt',
      'COPY --chown=appuser:appuser . .',
      'USER appuser',
      `EXPOSE ${port}`,
      `CMD ${jsonExec(start)}`,
    ].join('\n'),
  go: ({ version = '1.23.4-bookworm', port = 8080 }) =>
    [
      NOTE,
      `FROM golang:${version} AS build`,
      'WORKDIR /src',
      'COPY go.* ./',
      'RUN go mod download',
      'COPY . .',
      'RUN CGO_ENABLED=0 go build -trimpath -o /out/app ./...',
      '',
      'FROM gcr.io/distroless/static-debian12:nonroot',
      'COPY --from=build /out/app /app',
      'USER nonroot:nonroot',
      `EXPOSE ${port}`,
      'ENTRYPOINT ["/app"]',
    ].join('\n'),
  java: ({ version = '21-jdk-jammy', port = 8080, start = 'java -jar app.jar' }) =>
    [
      NOTE,
      `FROM eclipse-temurin:${version} AS build`,
      'WORKDIR /src',
      'COPY . .',
      'RUN ./mvnw -q -DskipTests package || ./gradlew --no-daemon build -x test',
      '',
      'FROM eclipse-temurin:21-jre-jammy',
      'RUN useradd --create-home --uid 1000 appuser',
      'WORKDIR /app',
      'COPY --from=build --chown=appuser:appuser /src/target/*.jar /app/app.jar',
      'USER appuser',
      `EXPOSE ${port}`,
      `CMD ${jsonExec(start)}`,
    ].join('\n'),
  generic: ({ port = 8080, start = 'sh -c "echo replace me"' }) =>
    [
      NOTE,
      '# TODO: replace the base image with a pinned, minimal image for your runtime.',
      'FROM alpine:3.20.3',
      'RUN adduser -D -u 1000 appuser',
      'WORKDIR /app',
      'COPY --chown=appuser:appuser . .',
      'USER appuser',
      `EXPOSE ${port}`,
      `CMD ${jsonExec(start)}`,
    ].join('\n'),
});

/** Render a command string as a JSON exec-form array for CMD/ENTRYPOINT. */
function jsonExec(cmd) {
  const parts = String(cmd).trim().split(/\s+/).filter(Boolean);
  return JSON.stringify(parts.length ? parts : ['true']);
}

/** Build a hardened Dockerfile for a language preset. */
function renderDockerfile(spec = {}) {
  const language = String(spec.language || 'generic').toLowerCase();
  const build = TEMPLATES[language] || TEMPLATES.generic;
  return `${build(spec)}\n`;
}

/** Build a .dockerignore that keeps secrets and cruft out of the build context. */
function renderDockerignore() {
  return [
    '.git',
    '.gitignore',
    'node_modules',
    'npm-debug.log',
    '**/__pycache__',
    '*.pyc',
    '.venv',
    'venv',
    'dist',
    'build',
    'target',
    '.env',
    '.env.*',
    '*.pem',
    '*.key',
    'id_rsa',
    '.aws',
    '.ssh',
    'secrets',
    'Dockerfile',
    '.dockerignore',
    '',
  ].join('\n');
}

const IMAGE_RE = /^[A-Za-z0-9][\w./:@-]{0,220}$/;
const NAME_RE = /^[A-Za-z0-9][\w.-]{0,127}$/;
const PORT_RE = /^\d{1,5}(:\d{1,5})?(\/(tcp|udp))?$/;
const ENV_NAME_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

function assertImage(ref) {
  const value = String(ref || '').trim();
  if (!IMAGE_RE.test(value)) throw new Error(`invalid image reference: "${ref}"`);
  return value;
}

/** Reject host-filesystem and docker-socket bind mounts; allow named/workspace binds only. */
function assertSafeVolume(spec, base) {
  const value = String(spec || '').trim();
  const [source, dest, ...rest] = value.split(':');
  if (!source || !dest || rest.length > 1) throw new Error(`invalid volume "${spec}" (use source:container[:ro])`);
  if (/docker\.sock/i.test(value)) throw new Error('refusing to mount the Docker socket');
  if (path.isAbsolute(source)) {
    const rel = path.relative(base, path.resolve(source));
    if (rel === '..' || rel.startsWith(`..${path.sep}`) || path.isAbsolute(rel)) {
      throw new Error(`refusing host bind mount outside the workspace: "${source}"`);
    }
  }
  return value;
}

function portArgs(ports = []) {
  return ports.flatMap((p) => {
    const v = String(p).trim();
    if (!PORT_RE.test(v)) throw new Error(`invalid port mapping: "${p}"`);
    return ['-p', v];
  });
}

/** --build-arg pairs, refusing secret-looking keys (they persist in image history). */
function buildArgPairs(map = {}) {
  return Object.entries(map).flatMap(([k, v]) => {
    if (!ENV_NAME_RE.test(k)) throw new Error(`invalid build-arg name: "${k}"`);
    if (SECRET_KEY_RE.test(k)) throw new Error(`refusing secret-looking build-arg "${k}" (it would persist in image layers; use BuildKit secrets)`);
    return ['--build-arg', `${k}=${String(v)}`];
  });
}

function envArgs(map = {}) {
  return Object.entries(map).flatMap(([k, v]) => {
    if (!ENV_NAME_RE.test(k)) throw new Error(`invalid env name: "${k}"`);
    return ['-e', `${k}=${String(v)}`];
  });
}

// ---- Tool factories -------------------------------------------------------

const dockerfileGenerateTool = defineTool(
  {
    name: 'dockerfile_generate',
    description:
      'Generate a HARDENED Dockerfile (+ .dockerignore) for a language preset (node|python|go|java|generic) ' +
      'and write it into the workspace. Pinned base image, non-root USER, secret-free build context. ' +
      'Prefer this over hand-writing a Dockerfile.',
    schema: (z) =>
      z.object({
        language: z.enum(['node', 'python', 'go', 'java', 'generic']).describe('runtime preset'),
        version: z.string().optional().describe('base image tag, e.g. "20.18.1-bookworm-slim"'),
        port: z.number().int().positive().optional().describe('port to EXPOSE'),
        start: z.string().optional().describe('start command, e.g. "node server.js"'),
        dir: z.string().optional().describe('workspace-relative directory to write into (default: root)'),
      }),
  },
  async (input, ctx) => {
    const dir = resolveWorkdir(ctx, input.dir);
    fs.mkdirSync(dir, { recursive: true });
    const dockerfile = renderDockerfile(input);
    const ignorePath = path.join(dir, '.dockerignore');
    fs.writeFileSync(path.join(dir, 'Dockerfile'), dockerfile, 'utf8');
    if (!fs.existsSync(ignorePath)) fs.writeFileSync(ignorePath, renderDockerignore(), 'utf8');
    return `✅ Wrote hardened Dockerfile + .dockerignore to ${dir}\n\n${dockerfile}`;
  }
);

const dockerBuildTool = defineTool(
  {
    name: 'docker_build',
    description: 'Build a Docker image from the workspace using the local Docker daemon (`docker build`).',
    schema: (z) =>
      z.object({
        tag: z.string().describe('image tag, e.g. "myapp:dev"'),
        dockerfile: z.string().optional().describe('workspace-relative Dockerfile path (default: ./Dockerfile)'),
        context: z.string().optional().describe('workspace-relative build context (default: .)'),
        buildArgs: z.record(z.string()).optional().describe('non-secret --build-arg values'),
      }),
  },
  async (input, ctx) => {
    const tag = assertImage(input.tag);
    const args = ['build', '-t', tag, ...buildArgPairs(input.buildArgs)];
    if (input.dockerfile) {
      resolveWorkdir(ctx, input.dockerfile);
      args.push('-f', input.dockerfile);
    }
    args.push(input.context ? relArg(ctx, input.context) : '.');
    return execTool({ ctx, label: 'docker build', command: 'docker', args, notFoundHint: 'Install Docker Desktop and ensure the daemon is running.' });
  }
);

const dockerRunTool = defineTool(
  {
    name: 'docker_run',
    description: 'Run a container on the local Docker daemon (`docker run`). Cannot mount the Docker socket or run privileged.',
    schema: (z) =>
      z.object({
        image: z.string().describe('image reference to run'),
        name: z.string().optional().describe('container name'),
        ports: z.array(z.string()).optional().describe('port maps like "8080:80"'),
        env: z.record(z.string()).optional().describe('environment variables for the container'),
        volumes: z.array(z.string()).optional().describe('binds "src:container[:ro]" — host paths must stay inside the workspace'),
        detach: z.boolean().optional().describe('run detached (-d)'),
        rm: z.boolean().optional().describe('remove on exit (--rm), default true'),
        command: z.array(z.string()).optional().describe('command + args to run in the container'),
      }),
  },
  async (input, ctx) => {
    const base = resolveWorkdir(ctx);
    const args = ['run'];
    if (input.rm !== false) args.push('--rm');
    if (input.detach) args.push('-d');
    if (input.name) args.push('--name', assertName(input.name));
    args.push(...portArgs(input.ports), ...envArgs(input.env));
    for (const v of input.volumes || []) args.push('-v', assertSafeVolume(v, base));
    args.push(assertImage(input.image));
    for (const c of input.command || []) args.push(String(c));
    return execTool({ ctx, label: 'docker run', command: 'docker', args, notFoundHint: 'Install Docker Desktop and ensure the daemon is running.' });
  }
);

const dockerComposeTool = defineTool(
  {
    name: 'docker_compose',
    description: 'Drive Docker Compose (`docker compose <up|down|build|ps|logs>`) for a local multi-service environment.',
    schema: (z) =>
      z.object({
        action: z.enum(['up', 'down', 'build', 'ps', 'logs']).describe('compose subcommand'),
        file: z.string().optional().describe('workspace-relative compose file (default: docker-compose.yml)'),
        detach: z.boolean().optional().describe('for "up": run detached (default true)'),
        dir: z.string().optional().describe('workspace-relative project directory'),
      }),
  },
  async (input, ctx) => {
    const args = ['compose'];
    if (input.file) {
      resolveWorkdir(ctx, input.file);
      args.push('-f', input.file);
    }
    args.push(input.action);
    if (input.action === 'up') args.push(input.detach === false ? '--abort-on-container-exit' : '-d');
    if (input.action === 'down') args.push('--remove-orphans');
    return execTool({ ctx, label: `docker compose ${input.action}`, command: 'docker', args, dir: input.dir, notFoundHint: 'Install Docker Desktop (Compose v2 ships with it).' });
  }
);

const dockerInfoTool = defineTool(
  {
    name: 'docker_info',
    description: 'Report local Docker availability and daemon status (`docker version` / `docker info`). Use to confirm Docker Desktop is running.',
    schema: (z) => z.object({}),
  },
  async (_input, ctx) =>
    execTool({ ctx, label: 'docker info', command: 'docker', args: ['version', '--format', '{{.Server.Version}}'], timeoutSec: 30, notFoundHint: 'Install Docker Desktop; then start it so the daemon socket is available.' })
);

function assertName(name) {
  const v = String(name || '').trim();
  if (!NAME_RE.test(v)) throw new Error(`invalid container name: "${name}"`);
  return v;
}

/** Validate a workspace-relative path and return it unchanged for use as an arg. */
function relArg(ctx, rel) {
  resolveWorkdir(ctx, rel);
  return rel;
}

const FACTORIES = Object.freeze({
  dockerfile_generate: dockerfileGenerateTool,
  docker_build: dockerBuildTool,
  docker_run: dockerRunTool,
  docker_compose: dockerComposeTool,
  docker_info: dockerInfoTool,
});

module.exports = {
  FACTORIES,
  renderDockerfile,
  renderDockerignore,
  assertImage,
  assertSafeVolume,
  buildArgPairs,
  portArgs,
  envArgs,
  jsonExec,
  TEMPLATES,
};
