#!/usr/bin/env bash
#
# gen-code-docs.sh — regenerate the code-graph documentation wiki.
#
# Runs `code-review-graph build` + `wiki`, normalizes the machine-specific
# absolute paths the tool embeds down to repo-relative paths, and syncs the
# resulting markdown into the tracked docs/code-graph/ directory.
#
# Output is deterministic: two runs on the same source produce byte-identical
# files. That determinism is what lets the pre-commit hook use a plain drift
# check (.githooks/pre-commit).
#
# Usage:  npm run docs:code   (or: bash scripts/gen-code-docs.sh)
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

OUT="docs/code-graph"                 # tracked, committed docs
WIKI=".code-review-graph/wiki"        # tool's raw output (gitignored)
HEADER='<!-- Generated by code-review-graph via scripts/gen-code-docs.sh. Do not edit by hand — run: npm run docs:code -->'

# --- locate the CLI (installed via `pipx install code-review-graph`) ---------
CRG=""
if command -v code-review-graph >/dev/null 2>&1; then
  CRG="code-review-graph"
elif [ -x "$HOME/.local/bin/code-review-graph" ]; then
  CRG="$HOME/.local/bin/code-review-graph"
else
  echo "error: 'code-review-graph' not found on PATH or in ~/.local/bin." >&2
  echo "       Install it with:  pipx install code-review-graph" >&2
  echo "       (see https://github.com/tirth8205/code-review-graph)" >&2
  exit 127
fi

# --- build the graph + wiki (quiet unless something fails) -------------------
LOG="$(mktemp)"
trap 'rm -f "$LOG"' EXIT
if ! "$CRG" build >"$LOG" 2>&1; then
  cat "$LOG" >&2
  echo "error: 'code-review-graph build' failed." >&2
  exit 1
fi
if ! "$CRG" wiki --force >"$LOG" 2>&1; then
  cat "$LOG" >&2
  echo "error: 'code-review-graph wiki' failed." >&2
  exit 1
fi

if [ ! -d "$WIKI" ]; then
  echo "error: expected wiki output at $WIKI but it does not exist." >&2
  exit 1
fi

# --- sync normalized markdown into the tracked docs dir ----------------------
mkdir -p "$OUT"
# Drop stale generated pages so removed communities disappear from the docs.
find "$OUT" -maxdepth 1 -type f -name '*.md' -delete

count=0
for f in "$WIKI"/*.md; do
  [ -e "$f" ] || continue
  name="$(basename "$f")"
  # Rewrite the absolute repo root to '.' so committed docs are portable and
  # produce no false drift across machines / git worktrees.
  {
    printf '%s\n\n' "$HEADER"
    sed "s#${ROOT}/#./#g; s#${ROOT}#.#g" "$f"
  } >"$OUT/$name"
  count=$((count + 1))
done

echo "Generated ${count} page(s) into ${OUT}/"
