"""Docker tools (port of agent/tools/docker.js).

Generate hardened build artifacts and drive the local Docker daemon. Everything
delegates to the ``docker`` CLI; nothing here re-implements the daemon protocol.

Security (infrastructure-misconfig checklist): generated Dockerfiles pin the
base image, run as a non-root USER, and ship a .dockerignore that keeps secrets
out of the build context. The run/build wrappers build their own argument
arrays, so ``--privileged``, ``--pid=host``, and a ``/var/run/docker.sock`` mount
are simply never expressible; secret-valued ``--build-arg``s are refused so
credentials cannot bake into image history.
"""

from __future__ import annotations

import json
import os
import re
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field

from ai_fleet.agent.tools.exec import (
    SECRET_KEY_RE,
    define_tool,
    exec_tool,
    resolve_workdir,
)

NOTE = "# Generated by AI Fleet — review before use. Pin digests for production."


def json_exec(cmd) -> str:
    """Render a command string as a JSON exec-form array for CMD/ENTRYPOINT."""
    parts = [p for p in re.split(r"\s+", str(cmd).strip()) if p]
    return json.dumps(parts if parts else ["true"], separators=(",", ":"))


def _node_template(spec):
    version = spec.get("version") or "20.18.1-bookworm-slim"
    port = spec.get("port") or 3000
    start = spec.get("start") or "node server.js"
    return "\n".join(
        [
            NOTE,
            f"FROM node:{version}",
            "ENV NODE_ENV=production",
            "WORKDIR /app",
            "COPY --chown=node:node package*.json ./",
            "RUN npm ci --omit=dev",
            "COPY --chown=node:node . .",
            "USER node",
            f"EXPOSE {port}",
            f"CMD {json_exec(start)}",
        ]
    )


def _python_template(spec):
    version = spec.get("version") or "3.12.7-slim-bookworm"
    port = spec.get("port") or 8000
    start = spec.get("start") or "python main.py"
    return "\n".join(
        [
            NOTE,
            f"FROM python:{version}",
            "ENV PYTHONDONTWRITEBYTECODE=1 \\",
            "    PYTHONUNBUFFERED=1",
            "RUN useradd --create-home --uid 1000 appuser",
            "WORKDIR /app",
            "COPY --chown=appuser:appuser requirements.txt ./",
            "RUN pip install --no-cache-dir -r requirements.txt",
            "COPY --chown=appuser:appuser . .",
            "USER appuser",
            f"EXPOSE {port}",
            f"CMD {json_exec(start)}",
        ]
    )


def _go_template(spec):
    version = spec.get("version") or "1.23.4-bookworm"
    port = spec.get("port") or 8080
    return "\n".join(
        [
            NOTE,
            f"FROM golang:{version} AS build",
            "WORKDIR /src",
            "COPY go.* ./",
            "RUN go mod download",
            "COPY . .",
            "RUN CGO_ENABLED=0 go build -trimpath -o /out/app ./...",
            "",
            "FROM gcr.io/distroless/static-debian12:nonroot",
            "COPY --from=build /out/app /app",
            "USER nonroot:nonroot",
            f"EXPOSE {port}",
            'ENTRYPOINT ["/app"]',
        ]
    )


def _java_template(spec):
    version = spec.get("version") or "21-jdk-jammy"
    port = spec.get("port") or 8080
    start = spec.get("start") or "java -jar app.jar"
    return "\n".join(
        [
            NOTE,
            f"FROM eclipse-temurin:{version} AS build",
            "WORKDIR /src",
            "COPY . .",
            "RUN ./mvnw -q -DskipTests package || ./gradlew --no-daemon build -x test",
            "",
            "FROM eclipse-temurin:21-jre-jammy",
            "RUN useradd --create-home --uid 1000 appuser",
            "WORKDIR /app",
            "COPY --from=build --chown=appuser:appuser /src/target/*.jar /app/app.jar",
            "USER appuser",
            f"EXPOSE {port}",
            f"CMD {json_exec(start)}",
        ]
    )


def _generic_template(spec):
    port = spec.get("port") or 8080
    start = spec.get("start") or 'sh -c "echo replace me"'
    return "\n".join(
        [
            NOTE,
            "# TODO: replace the base image with a pinned, minimal image for your runtime.",
            "FROM alpine:3.20.3",
            "RUN adduser -D -u 1000 appuser",
            "WORKDIR /app",
            "COPY --chown=appuser:appuser . .",
            "USER appuser",
            f"EXPOSE {port}",
            f"CMD {json_exec(start)}",
        ]
    )


TEMPLATES = {
    "node": _node_template,
    "python": _python_template,
    "go": _go_template,
    "java": _java_template,
    "generic": _generic_template,
}


def render_dockerfile(spec=None) -> str:
    """Build a hardened Dockerfile for a language preset."""
    spec = spec or {}
    language = str(spec.get("language") or "generic").lower()
    build = TEMPLATES.get(language, TEMPLATES["generic"])
    return f"{build(spec)}\n"


def render_dockerignore() -> str:
    """Build a .dockerignore that keeps secrets and cruft out of the build context."""
    return "\n".join(
        [
            ".git",
            ".gitignore",
            "node_modules",
            "npm-debug.log",
            "**/__pycache__",
            "*.pyc",
            ".venv",
            "venv",
            "dist",
            "build",
            "target",
            ".env",
            ".env.*",
            "*.pem",
            "*.key",
            "id_rsa",
            ".aws",
            ".ssh",
            "secrets",
            "Dockerfile",
            ".dockerignore",
            "",
        ]
    )


IMAGE_RE = re.compile(r"^[A-Za-z0-9][\w./:@-]{0,220}$", re.ASCII)
NAME_RE = re.compile(r"^[A-Za-z0-9][\w.-]{0,127}$", re.ASCII)
PORT_RE = re.compile(r"^\d{1,5}(:\d{1,5})?(/(tcp|udp))?$")
ENV_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def assert_image(ref):
    value = str(ref or "").strip()
    if not IMAGE_RE.match(value):
        raise Exception(f'invalid image reference: "{ref}"')
    return value


def assert_safe_volume(spec, base):
    """Reject host-filesystem and docker-socket bind mounts; allow named/workspace binds only."""
    value = str(spec or "").strip()
    pieces = value.split(":")
    source = pieces[0] if len(pieces) > 0 else ""
    dest = pieces[1] if len(pieces) > 1 else None
    rest = pieces[2:]
    if not source or not dest or len(rest) > 1:
        raise Exception(f'invalid volume "{spec}" (use source:container[:ro])')
    if re.search(r"docker\.sock", value, re.IGNORECASE):
        raise Exception("refusing to mount the Docker socket")
    if os.path.isabs(source):
        rel = os.path.relpath(os.path.abspath(source), base)
        if rel == ".." or rel.startswith(".." + os.sep) or os.path.isabs(rel):
            raise Exception(f'refusing host bind mount outside the workspace: "{source}"')
    return value


def port_args(ports=None):
    out = []
    for p in ports or []:
        v = str(p).strip()
        if not PORT_RE.match(v):
            raise Exception(f'invalid port mapping: "{p}"')
        out.extend(["-p", v])
    return out


def build_arg_pairs(map_=None):
    """--build-arg pairs, refusing secret-looking keys (they persist in image history)."""
    out = []
    for k, v in (map_ or {}).items():
        if not ENV_NAME_RE.match(k):
            raise Exception(f'invalid build-arg name: "{k}"')
        if SECRET_KEY_RE.search(k):
            raise Exception(
                f'refusing secret-looking build-arg "{k}" (it would persist in image layers; use BuildKit secrets)'
            )
        out.extend(["--build-arg", f"{k}={v}"])
    return out


def env_args(map_=None):
    out = []
    for k, v in (map_ or {}).items():
        if not ENV_NAME_RE.match(k):
            raise Exception(f'invalid env name: "{k}"')
        out.extend(["-e", f"{k}={v}"])
    return out


def assert_name(name):
    v = str(name or "").strip()
    if not NAME_RE.match(v):
        raise Exception(f'invalid container name: "{name}"')
    return v


def _rel_arg(ctx, rel):
    """Validate a workspace-relative path and return it unchanged for use as an arg."""
    resolve_workdir(ctx, rel)
    return rel


# ---- Schemas --------------------------------------------------------------


class _DockerfileGenerateSchema(BaseModel):
    language: Literal["node", "python", "go", "java", "generic"] = Field(description="runtime preset")
    version: Optional[str] = Field(default=None, description='base image tag, e.g. "20.18.1-bookworm-slim"')
    port: Optional[int] = Field(default=None, description="port to EXPOSE")
    start: Optional[str] = Field(default=None, description='start command, e.g. "node server.js"')
    dir: Optional[str] = Field(default=None, description="workspace-relative directory to write into (default: root)")


class _DockerBuildSchema(BaseModel):
    tag: str = Field(description='image tag, e.g. "myapp:dev"')
    dockerfile: Optional[str] = Field(default=None, description="workspace-relative Dockerfile path (default: ./Dockerfile)")
    context: Optional[str] = Field(default=None, description="workspace-relative build context (default: .)")
    buildArgs: Optional[Dict[str, str]] = Field(default=None, description="non-secret --build-arg values")


class _DockerRunSchema(BaseModel):
    image: str = Field(description="image reference to run")
    name: Optional[str] = Field(default=None, description="container name")
    ports: Optional[List[str]] = Field(default=None, description='port maps like "8080:80"')
    env: Optional[Dict[str, str]] = Field(default=None, description="environment variables for the container")
    volumes: Optional[List[str]] = Field(default=None, description='binds "src:container[:ro]" — host paths must stay inside the workspace')
    detach: Optional[bool] = Field(default=None, description="run detached (-d)")
    rm: Optional[bool] = Field(default=None, description="remove on exit (--rm), default true")
    command: Optional[List[str]] = Field(default=None, description="command + args to run in the container")


class _DockerComposeSchema(BaseModel):
    action: Literal["up", "down", "build", "ps", "logs"] = Field(description="compose subcommand")
    file: Optional[str] = Field(default=None, description="workspace-relative compose file (default: docker-compose.yml)")
    detach: Optional[bool] = Field(default=None, description='for "up": run detached (default true)')
    dir: Optional[str] = Field(default=None, description="workspace-relative project directory")


class _DockerInfoSchema(BaseModel):
    pass


# ---- Tool handlers --------------------------------------------------------


async def _dockerfile_generate(input, ctx):
    dir_ = resolve_workdir(ctx, input.get("dir"))
    os.makedirs(dir_, exist_ok=True)
    dockerfile = render_dockerfile(input)
    ignore_path = os.path.join(dir_, ".dockerignore")
    with open(os.path.join(dir_, "Dockerfile"), "w", encoding="utf-8") as f:
        f.write(dockerfile)
    if not os.path.exists(ignore_path):
        with open(ignore_path, "w", encoding="utf-8") as f:
            f.write(render_dockerignore())
    return f"✅ Wrote hardened Dockerfile + .dockerignore to {dir_}\n\n{dockerfile}"


async def _docker_build(input, ctx):
    tag = assert_image(input.get("tag"))
    args = ["build", "-t", tag, *build_arg_pairs(input.get("buildArgs"))]
    if input.get("dockerfile"):
        resolve_workdir(ctx, input["dockerfile"])
        args.extend(["-f", input["dockerfile"]])
    args.append(_rel_arg(ctx, input["context"]) if input.get("context") else ".")
    return await exec_tool(
        ctx=ctx,
        label="docker build",
        command="docker",
        args=args,
        not_found_hint="Install Docker Desktop and ensure the daemon is running.",
    )


async def _docker_run(input, ctx):
    base = resolve_workdir(ctx)
    args = ["run"]
    if input.get("rm") is not False:
        args.append("--rm")
    if input.get("detach"):
        args.append("-d")
    if input.get("name"):
        args.extend(["--name", assert_name(input["name"])])
    args.extend(port_args(input.get("ports")))
    args.extend(env_args(input.get("env")))
    for v in input.get("volumes") or []:
        args.extend(["-v", assert_safe_volume(v, base)])
    args.append(assert_image(input.get("image")))
    for c in input.get("command") or []:
        args.append(str(c))
    return await exec_tool(
        ctx=ctx,
        label="docker run",
        command="docker",
        args=args,
        not_found_hint="Install Docker Desktop and ensure the daemon is running.",
    )


async def _docker_compose(input, ctx):
    args = ["compose"]
    if input.get("file"):
        resolve_workdir(ctx, input["file"])
        args.extend(["-f", input["file"]])
    action = input.get("action")
    args.append(action)
    if action == "up":
        args.append("--abort-on-container-exit" if input.get("detach") is False else "-d")
    if action == "down":
        args.append("--remove-orphans")
    return await exec_tool(
        ctx=ctx,
        label=f"docker compose {action}",
        command="docker",
        args=args,
        dir=input.get("dir"),
        not_found_hint="Install Docker Desktop (Compose v2 ships with it).",
    )


async def _docker_info(input, ctx):
    return await exec_tool(
        ctx=ctx,
        label="docker info",
        command="docker",
        args=["version", "--format", "{{.Server.Version}}"],
        timeout_sec=30,
        not_found_hint="Install Docker Desktop; then start it so the daemon socket is available.",
    )


dockerfile_generate_tool = define_tool(
    {
        "name": "dockerfile_generate",
        "description": (
            "Generate a HARDENED Dockerfile (+ .dockerignore) for a language preset (node|python|go|java|generic) "
            "and write it into the workspace. Pinned base image, non-root USER, secret-free build context. "
            "Prefer this over hand-writing a Dockerfile."
        ),
        "schema": _DockerfileGenerateSchema,
    },
    _dockerfile_generate,
)

docker_build_tool = define_tool(
    {
        "name": "docker_build",
        "description": "Build a Docker image from the workspace using the local Docker daemon (`docker build`).",
        "schema": _DockerBuildSchema,
    },
    _docker_build,
)

docker_run_tool = define_tool(
    {
        "name": "docker_run",
        "description": "Run a container on the local Docker daemon (`docker run`). Cannot mount the Docker socket or run privileged.",
        "schema": _DockerRunSchema,
    },
    _docker_run,
)

docker_compose_tool = define_tool(
    {
        "name": "docker_compose",
        "description": "Drive Docker Compose (`docker compose <up|down|build|ps|logs>`) for a local multi-service environment.",
        "schema": _DockerComposeSchema,
    },
    _docker_compose,
)

docker_info_tool = define_tool(
    {
        "name": "docker_info",
        "description": "Report local Docker availability and daemon status (`docker version` / `docker info`). Use to confirm Docker Desktop is running.",
        "schema": _DockerInfoSchema,
    },
    _docker_info,
)

FACTORIES = {
    "dockerfile_generate": dockerfile_generate_tool,
    "docker_build": docker_build_tool,
    "docker_run": docker_run_tool,
    "docker_compose": docker_compose_tool,
    "docker_info": docker_info_tool,
}
